"""Literal public validator and error identifiers."""
KEYWORD = "UsdAecoWallValidators"
WALLKINDMISMATCH_CHECKER = "usdAecoWallValidators:WallKindMismatchChecker"
WALLKINDMISMATCH = "WallKindMismatch"
WALLMISSINGAXIS_CHECKER = "usdAecoWallValidators:WallMissingAxisChecker"
WALLMISSINGAXIS = "WallMissingAxis"
WALLJOINASYMMETRIC_CHECKER = "usdAecoWallValidators:WallJoinAsymmetricChecker"
WALLJOINASYMMETRIC = "WallJoinAsymmetric"
WALLJOINEDENDEXTENDED_CHECKER = "usdAecoWallValidators:WallJoinedEndExtendedChecker"
WALLJOINEDENDEXTENDED = "WallJoinedEndExtended"
WALLOPENINGOUTSIDEHOST_CHECKER = "usdAecoWallValidators:WallOpeningOutsideHostChecker"
WALLOPENINGOUTSIDEHOST = "WallOpeningOutsideHost"
WALLSIZEMISMATCH_CHECKER = "usdAecoWallValidators:WallSizeMismatchChecker"
WALLSIZEMISMATCH = "WallSizeMismatch"
ERROR_NAMES = ['WallKindMismatch', 'WallMissingAxis', 'WallJoinAsymmetric', 'WallJoinedEndExtended', 'WallOpeningOutsideHost', 'WallSizeMismatch']
